name: "Pull request"

on:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v6.0.2

      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: enhanced
          cache-read-only: false
          cache-encryption-key: ${{ env.GRADLE_ENCRYPTION_KEY }}

      - name: "Assemble desktop application"
        shell: bash
        run: ./gradlew :desktopApp:assemble

      - name: "Assemble Android application"
        shell: bash
        run: ./gradlew :androidApp:assemble

      - name: "Run unit tests"
        shell: bash
        run: |
          ./gradlew :shared:allTests
          ./gradlew :desktopApp:test
          ./gradlew :androidApp:testDebugUnitTest

      - name: "Verify code coverage"
        shell: bash
        run: ./gradlew koverVerify

      - name: "Detekt"
        shell: bash
        run: |
          ./gradlew :shared:detektCommonMain
          ./gradlew :shared:detektJvmMain
          ./gradlew :shared:detektAndroidMain
          ./gradlew :desktopApp:detektMain
          ./gradlew :androidApp:detektMain
